/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZuOU036eyCP
*/

import { Header } from '@/ihc/header'
import { PkgCard } from '@/ihc/pkgcard'

export function Homepage() {
  return (
    <div className="bg-background text-foreground min-h-screen">
      <Header />
      <main className="container mx-auto px-4 md:px-6 py-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {[
            {
              name: "react",
              description: "A JavaScript library for building user interfaces",
              version: "18.2.0",
              downloads: "1.2M",
              manager: "npm",
              dependencies: 15,
            },
            {
              name: "tailwindcss",
              description: "A utility-first CSS framework for rapid UI development",
              version: "3.3.1",
              downloads: "800K",
              manager: "npm",
              dependencies: 8,
            },
            {
              name: "express",
              description: "Fast, unopinionated, minimalist web application framework for Node.js",
              version: "4.18.2",
              downloads: "500K",
              manager: "npm",
              dependencies: 12,
            },
            {
              name: "django",
              description:
                "A high-level Python web framework that encourages rapid development and clean, pragmatic design",
              version: "4.1.7",
              downloads: "300K",
              manager: "pip",
              dependencies: 20,
            },
            {
              name: "axios",
              description: "Promise based HTTP client for the browser and Node.js",
              version: "1.3.3",
              downloads: "400K",
              manager: "npm",
              dependencies: 6,
            },
            {
              name: "flutter",
              description:
                "Google's UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase",
              version: "3.7.6",
              downloads: "200K",
              manager: "pub",
              dependencies: 18,
            },
            {
              name: "redis",
              description:
                "An open-source, in-memory data structure store, used as a database, cache, and message broker",
              version: "7.0.8",
              downloads: "150K",
              manager: "apt",
              dependencies: 10,
            },
            {
              name: "elixir",
              description:
                "A dynamic, functional language designed for building scalable and maintainable applications",
              version: "1.14.3",
              downloads: "100K",
              manager: "hex",
              dependencies: 14,
            },
          ].map((pkg, index) => (
            <PkgCard key={index} {...pkg} />
          ))}
        </div>
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {[
            { name: "vue", dependencies: 22, downloads: "800K", manager: "npm", version: "3.2.47" },
            { name: "angular", dependencies: 18, downloads: "600K", manager: "npm", version: "15.2.0" },
            { name: "react-native", dependencies: 16, downloads: "400K", manager: "npm", version: "0.71.3" },
            { name: "laravel", dependencies: 24, downloads: "300K", manager: "composer", version: "9.5.1" },
            { name: "spring-boot", dependencies: 20, downloads: "250K", manager: "maven", version: "2.7.8" },
            { name: "symfony", dependencies: 28, downloads: "200K", manager: "composer", version: "6.2.6" },
            { name: "ruby-on-rails", dependencies: 14, downloads: "180K", manager: "gem", version: "7.0.4" },
            {
              name: "asp-net-core",
              dependencies: 22,
              downloads: "150K",
              manager: "nuget",
              version: "7.0.3",
            },
          ].map((pkg, index) => (
            <div
              key={index}
              className="bg-card shadow-sm hover:shadow-md transition-shadow rounded-full px-4 py-2 flex items-center justify-between"
            >
              <div className="text-sm font-medium">{pkg.manager}</div>
              <div className="text-sm font-medium">{pkg.name}</div>
              <div className="text-sm font-medium">v{pkg.version}</div>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}